# Generated by Django 5.2.17 on 2026-08-05 17:57

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scramble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves', models.CharField(max_length=200)),
                ('nonce', models.CharField(db_index=True, default=core.models._new_nonce, max_length=64, unique=True)),
                ('signature', models.CharField(max_length=128)),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrambles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-issued_at',),
            },
        ),
        migrations.CreateModel(
            name='WaitlistSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('last_campaign', models.CharField(blank=True, db_index=True, max_length=64)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('send_failures', models.PositiveIntegerField(default=0)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_token', models.CharField(db_index=True, default=core.models._new_nonce, max_length=64, unique=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['last_campaign', 'unsubscribed_at'], name='core_waitli_last_ca_572d9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('derived_seconds', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('frame_count', models.PositiveIntegerField()),
                ('fps', models.FloatField()),
                ('observed_moves', models.PositiveIntegerField()),
                ('observed_moves_after_stop', models.PositiveIntegerField(default=0)),
                ('post_stop_seconds', models.FloatField(blank=True, null=True)),
                ('evidence_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('claimed_seconds', models.FloatField(blank=True, null=True)),
                ('claim_discrepancy', models.FloatField(blank=True, null=True)),
                ('verdict', models.CharField(choices=[('verified', 'Verified'), ('rejected', 'Rejected'), ('review', 'Needs review')], db_index=True, max_length=16)),
                ('reject_reasons', models.JSONField(blank=True, default=list)),
                ('review_reasons', models.JSONField(blank=True, default=list)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('reverified', models.BooleanField(default=False)),
                ('scramble', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='solve', to='core.scramble')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-received_at',),
                'indexes': [models.Index(fields=['verdict', '-received_at'], name='core_solve_verdict_23b20b_idx')],
            },
        ),
    ]
