# Generated by Django 5.2.17 on 2026-08-05 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configure_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, db_index=True, max_length=2)),
                ('rating', models.IntegerField(db_index=True, default=1000)),
                ('best_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('is_founder', models.BooleanField(default=False)),
                ('username_changed_at', models.DateTimeField(blank=True, null=True)),
                ('email_changed_at', models.DateTimeField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('previous_usernames', models.JSONField(blank=True, default=list)),
                ('name_flags', models.JSONField(blank=True, default=list)),
                ('needs_name_review', models.BooleanField(db_index=True, default=False)),
                ('avatar_status', models.CharField(choices=[('none', 'No upload'), ('pending', 'Awaiting review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='none', max_length=16)),
                ('avatar_path', models.CharField(blank=True, max_length=300)),
                ('avatar_updated_at', models.DateTimeField(blank=True, null=True)),
                ('notify_invites', models.BooleanField(default=True)),
                ('notify_recap', models.BooleanField(default=False)),
                ('notify_pb', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='solve',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solves_against', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solve',
            name='rating_delta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solve',
            name='result',
            field=models.CharField(choices=[('solo', 'Solo trial'), ('win', 'Win'), ('loss', 'Loss')], db_index=True, default='solo', max_length=8),
        ),
        migrations.AddIndex(
            model_name='solve',
            index=models.Index(fields=['user', '-received_at'], name='core_solve_user_id_f5e5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='solve',
            index=models.Index(fields=['user', 'verdict', 'derived_seconds'], name='core_solve_user_id_6983f6_idx'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
