# Generated by Django 5.2.17 on 2026-08-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_solve_opponent_solve_rating_delta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solve',
            name='analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
