# Generated by Django 5.2.17 on 2026-08-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_solve_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
