# Generated by Django 5.2.17 on 2026-08-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_preset',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
