"""
Server-side scramble generation and signing.

The client must never choose its own scramble — given the choice it picks one
it already has a solution for, and the whole "solver-following" defence in
`anticheat_gate.py` evaporates because the attacker no longer needs a solver
at run time.
"""

import hashlib
import hmac
import secrets

from django.conf import settings

FACES = "UDLRFB"
#: Opposite faces. Two consecutive turns of opposite faces commute, so
#: "R L R" contains a redundancy a scramble should not have; excluding the
#: same face is not enough on its own.
OPPOSITE = {"U": "D", "D": "U", "L": "R", "R": "L", "F": "B", "B": "F"}
SUFFIXES = ("", "'", "2")
DEFAULT_LENGTH = 20   # WCA-style random-move scramble, half-turn metric


def generate(length: int = DEFAULT_LENGTH) -> str:
    """A random-move scramble in WCA notation.

    Random-MOVE, not random-STATE. The difference matters and is a known
    shortcut: a proper WCA scramble is generated by picking a uniformly
    random cube state and solving it, which guarantees a minimum difficulty.
    Random-move sequences occasionally cancel into something easier. At 20
    moves that is rare enough not to matter for a beta, and the fix (drive
    the vendored two-phase solver in cv/solver/twophase) costs 30-60s of
    table precomputation on first call — worth doing before anything with
    prizes on it, not before the first users.

    `secrets` rather than `random`: this is an adversarial context, and a
    predictable scramble stream would let someone precompute solutions for
    scrambles that have not been issued yet.
    """
    moves: list[str] = []
    prev = prev2 = ""
    while len(moves) < length:
        face = FACES[secrets.randbelow(len(FACES))]
        # No repeat of the last face (R R is one turn), and no repeat of the
        # face before last when they commute (R L R collapses to R2 L).
        if face == prev:
            continue
        if face == OPPOSITE.get(prev, "") and face == prev2:
            continue
        suffix = SUFFIXES[secrets.randbelow(len(SUFFIXES))]
        moves.append(face + suffix)
        prev, prev2 = face, prev
    return " ".join(moves)


def sign(moves: str, nonce: str) -> str:
    """HMAC over the scramble and its nonce.

    Binds the two together so a scramble cannot be lifted from one issuance
    and presented under another's nonce. Uses the Django secret key, which is
    why settings.py refuses to start in production without a real one.
    """
    msg = f"{moves}|{nonce}".encode()
    return hmac.new(settings.SECRET_KEY.encode(), msg, hashlib.sha256).hexdigest()


def verify(moves: str, nonce: str, signature: str) -> bool:
    """Constant-time signature check."""
    return hmac.compare_digest(sign(moves, nonce), signature or "")
